In [1]:
import pandas as pd
df = pd.read_csv('Downloads/spam.csv')

In [2]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [3]:
df.drop(['Unnamed: 0','label_num'],axis = 'columns',inplace = True)

In [4]:
df.head()

label                                               text
0   ham  Subject: enron methanol ; meter # : 988291\r\n...
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3  spam  Subject: photoshop , windows , office . cheap ...
4   ham  Subject: re : indian springs\r\nthis deal is t...

In [5]:
df.describe()

label                                               text
count   5171                                               5171
unique     2                                               4993
top      ham  Subject: calpine daily gas nomination\r\n>\r\n...
freq    3672                                                 20

In [6]:
df['spam'] = df['label'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

label                                               text  spam
0   ham  Subject: enron methanol ; meter # : 988291\r\n...     0
1   ham  Subject: hpl nom for january 9 , 2001\r\n( see...     0
2   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3  spam  Subject: photoshop , windows , office . cheap ...     1
4   ham  Subject: re : indian springs\r\nthis deal is t...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.text,df.spam,test_size = 0.25, random_state =100)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [14]:
X_train_count = v.fit_transform(X_train.values)

In [15]:
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [20]:
emails = [" Hey can we play football tommorow?",
         "upto 20% discount and rewards exclusive offer just for you"]

emails_count = v.transform(emails)


In [21]:
model.predict(emails_count)

array([0, 1], dtype=int64)

In [22]:
X_test_count = v.transform(X_test)

In [23]:
model.score(X_test_count,y_test)

0.9760247486465584

In [24]:
from sklearn.pipeline import Pipeline

In [25]:
clf = Pipeline([('vectorizer',CountVectorizer()),('nb', MultinomialNB())])

In [26]:
clf.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [27]:
clf.score(X_test,y_test)

0.9760247486465584

In [29]:
clf.predict(emails)

array([0, 1], dtype=int64)